-- AseemBox 低代码平台初始化脚本
-- 创建元数据存储表

-- 模型定义表
CREATE TABLE IF NOT EXISTS `t_aseembox_model_definition` (
  `id` VARCHAR(32) NOT NULL COMMENT '主键ID',
  `tenant` VARCHAR(64) NOT NULL COMMENT '租户代码',
  `code` VARCHAR(100) NOT NULL COMMENT '模型代码',
  `name` VARCHAR(200) NOT NULL COMMENT '模型名称',
  `description` TEXT NULL COMMENT '模型描述',
  `tableName` VARCHAR(100) NULL COMMENT '物理表名',
  `config` JSON NULL COMMENT '模型配置',
  `status` VARCHAR(20) NOT NULL DEFAULT 'draft' COMMENT '状态: draft, published, deprecated',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `creatorId` VARCHAR(32) NULL COMMENT '创建人ID',
  `creatorName` VARCHAR(100) NULL COMMENT '创建人姓名',
  `modifierAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modifierId` VARCHAR(32) NULL COMMENT '修改人ID',
  `modifierName` VARCHAR(100) NULL COMMENT '修改人姓名',
  `isRemoved` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
  PRIMARY KEY (`id`),
  INDEX `idx_tenant` (`tenant`),
  INDEX `idx_code` (`code`),
  INDEX `idx_status` (`status`),
  INDEX `idx_is_removed` (`isRemoved`),
  UNIQUE KEY `uk_tenant_code` (`tenant`, `code`, `isRemoved`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型定义表';

-- 字段定义表
CREATE TABLE IF NOT EXISTS `t_aseembox_field_definition` (
  `id` VARCHAR(32) NOT NULL COMMENT '主键ID',
  `tenant` VARCHAR(64) NOT NULL COMMENT '租户代码',
  `modelId` VARCHAR(32) NOT NULL COMMENT '所属模型ID',
  `code` VARCHAR(100) NOT NULL COMMENT '字段代码',
  `name` VARCHAR(200) NOT NULL COMMENT '字段名称',
  `description` TEXT NULL COMMENT '字段描述',
  `type` VARCHAR(50) NOT NULL COMMENT '字段类型',
  `dbType` VARCHAR(100) NULL COMMENT '数据库类型',
  `constraints` JSON NULL COMMENT '字段约束',
  `validations` JSON NULL COMMENT '验证规则',
  `sortOrder` INT NOT NULL DEFAULT 0 COMMENT '排序序号',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `creatorId` VARCHAR(32) NULL COMMENT '创建人ID',
  `creatorName` VARCHAR(100) NULL COMMENT '创建人姓名',
  `modifierAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modifierId` VARCHAR(32) NULL COMMENT '修改人ID',
  `modifierName` VARCHAR(100) NULL COMMENT '修改人姓名',
  `isRemoved` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
  PRIMARY KEY (`id`),
  INDEX `idx_tenant` (`tenant`),
  INDEX `idx_model_id` (`modelId`),
  INDEX `idx_code` (`code`),
  INDEX `idx_is_removed` (`isRemoved`),
  UNIQUE KEY `uk_model_code` (`modelId`, `code`, `isRemoved`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='字段定义表';

-- 关联定义表
CREATE TABLE IF NOT EXISTS `t_aseembox_relation_definition` (
  `id` VARCHAR(32) NOT NULL COMMENT '主键ID',
  `tenant` VARCHAR(64) NOT NULL COMMENT '租户代码',
  `code` VARCHAR(100) NOT NULL COMMENT '关联代码',
  `name` VARCHAR(200) NOT NULL COMMENT '关联名称',
  `description` TEXT NULL COMMENT '关联描述',
  `sourceModelId` VARCHAR(32) NOT NULL COMMENT '源模型ID',
  `sourceModel` VARCHAR(100) NOT NULL COMMENT '源模型代码',
  `targetModelId` VARCHAR(32) NOT NULL COMMENT '目标模型ID',
  `targetModel` VARCHAR(100) NOT NULL COMMENT '目标模型代码',
  `type` VARCHAR(50) NOT NULL COMMENT '关联类型',
  `joinConfig` JSON NOT NULL COMMENT 'JOIN配置',
  `includeFields` JSON NULL COMMENT '包含字段',
  `fieldAliases` JSON NULL COMMENT '字段别名',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `creatorId` VARCHAR(32) NULL COMMENT '创建人ID',
  `creatorName` VARCHAR(100) NULL COMMENT '创建人姓名',
  `modifierAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modifierId` VARCHAR(32) NULL COMMENT '修改人ID',
  `modifierName` VARCHAR(100) NULL COMMENT '修改人姓名',
  `isRemoved` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
  PRIMARY KEY (`id`),
  INDEX `idx_tenant` (`tenant`),
  INDEX `idx_source_model` (`sourceModelId`),
  INDEX `idx_target_model` (`targetModelId`),
  INDEX `idx_is_removed` (`isRemoved`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='关联定义表';

-- 操作定义表
CREATE TABLE IF NOT EXISTS `t_aseembox_action_definition` (
  `id` VARCHAR(32) NOT NULL COMMENT '主键ID',
  `tenant` VARCHAR(64) NOT NULL COMMENT '租户代码',
  `modelId` VARCHAR(32) NOT NULL COMMENT '所属模型ID',
  `code` VARCHAR(100) NOT NULL COMMENT '操作代码',
  `name` VARCHAR(200) NOT NULL COMMENT '操作名称',
  `description` TEXT NULL COMMENT '操作描述',
  `type` VARCHAR(50) NOT NULL COMMENT '操作类型',
  `permissions` JSON NULL COMMENT '权限配置',
  `hooks` JSON NULL COMMENT '钩子配置',
  `queryConfig` JSON NULL COMMENT '查询配置',
  `mutationConfig` JSON NULL COMMENT '变更配置',
  `customConfig` JSON NULL COMMENT '自定义配置',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `creatorId` VARCHAR(32) NULL COMMENT '创建人ID',
  `creatorName` VARCHAR(100) NULL COMMENT '创建人姓名',
  `modifierAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modifierId` VARCHAR(32) NULL COMMENT '修改人ID',
  `modifierName` VARCHAR(100) NULL COMMENT '修改人姓名',
  `isRemoved` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
  PRIMARY KEY (`id`),
  INDEX `idx_tenant` (`tenant`),
  INDEX `idx_model_id` (`modelId`),
  INDEX `idx_code` (`code`),
  INDEX `idx_type` (`type`),
  INDEX `idx_is_removed` (`isRemoved`),
  UNIQUE KEY `uk_model_code` (`modelId`, `code`, `isRemoved`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作定义表';
